### ISSUE TITLE
Container does not start because of '/etc/localtime.dpkg-new'

### ISSUE THREAD

**Issue by bousquetfrederic** [aptalca/docker-dolphin#4]
When I try to run the container following the indications in the Readme, it fails with error message:

> *** Running /etc/my_init.d/00_config.sh...
> mv: cannot move '/etc/localtime.dpkg-new' to '/etc/localtime': Device or resource busy
> *** /etc/my_init.d/00_config.sh failed with status 1

I am guessing this is because of the following parameter in the docker command: 
> -v /etc/localtime:/etc/localtime:ro

**Comment by aptalca** [comment]
Yup, it causes issues on some hosts.

Instead of that parameter, try adding this: `-e TZ=America/New_York` you can use the timezone values from here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
